management:
  endpoints:
    web:
      exposure:
        include: "*"
custom:
  servers:
    - dev.example.com
    - another.example.com
acme:
  remote-address: 127.0.0.1
  security:
    username: admin
    roles:
      - ADMIN
      - USER
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
